[package]
name = "ddns-update"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
regex = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
retry = "2.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
signal-hook = "0.3"
