name: Continuous Integration

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run fmt command
        run: cargo fmt --all -- --check --color always

      - name: Run clippy command
        run: cargo clippy --all-targets --all-features --workspace -- -D warnings

  deploy:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PACKAGE_NAME: ${{github.event.repository.name}}-${{matrix.platform.target}}-${{github.ref_name}}
    strategy:
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate version
        run: |
          export CARGO_VERSION=v$(awk '/^version/ {print $3}' Cargo.toml | head -1 | tr -d '"')
          export GIT_VERSION=${{github.ref_name}}
          echo "Cargo version: $CARGO_VERSION"
          echo "Git version: $GIT_VERSION"
          if [[ "${CARGO_VERSION}" != "$GIT_VERSION" ]]; then
            echo "Tag version and Cargo.toml version don't match" 1>&2
            exit 1
          fi

      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ddns-update
          target: ${{ matrix.platform.target }}
